
XPROTO_PACKAGE=xcb-proto-${XPROTO_VERSION}
DOWNLOAD_PATH=resources
XML_TARBALL=http://xcb.freedesktop.org/dist/${XPROTO_PACKAGE}.tar.gz
XML_SOURCE_DIR=${DOWNLOAD_PATH}/${XPROTO_PACKAGE}/src
XML_DIR=${DOWNLOAD_PATH}/${XPROTO_PACKAGE}/patched
XML_FILES=*.xml
